/**
 * scar_vocab.js — the scar form's vocabulary, defined once.
 *
 * Three surfaces ask a labeler to describe a scar: the main form (static markup
 * in index.html, bound by scar_form.js), the sidebar track editor and the triage
 * card (both generated by scar_form_helpers.js). Each carried its own copy of the
 * type list, the zone labels, the colours and the sides, and they had already
 * drifted:
 *
 *   - the main form offered Right/Left; the helpers offered Left/Right/**Both**
 *   - zone labels were "FLANK" in one and "Flank" in the other
 *   - PINK was #ff9999 in one and #ff9bb0 in the other
 *
 * The side split is the one that matters. A scar sits on ONE flank; "Both" is the
 * ENCOUNTER-level `sides_visible` question ("which sides did I get to see"),
 * which is a statement about camera coverage, not about a mark on an animal.
 * Letting it into a per-scar field is the same category error CLAUDE.md warns
 * about under Stream D — `sides_visible` was 58.2% accurate as a per-frame flank
 * against 97.2% for the real thing. `auto_side` and `determine_side` are
 * Left/Right, so a human "Both" cannot be compared with either.
 *
 * This module owns the DATA. The two renderers stay separate on purpose:
 * scar_form.js binds pre-existing server-rendered markup, scar_form_helpers.js
 * generates prefixed markup so N instances can coexist. Different jobs, same
 * words.
 *
 * The static markup in templates/index.html is still a second copy of the option
 * ELEMENTS; tests/test_scar_vocab.py asserts it agrees with this file, so drift
 * is a test failure rather than a discovery.
 */
"use strict";

(function (root) {

/** The 12 scar types, in the order they are offered. Mirrors models.ScarType. */
const SCAR_TYPES = [
  "GRAB", "BITE", "SCRATCH", "SCRAPE", "CANINE", "COOKIE",
  "GEAR", "PROP", "TAGS", "SQUID", "COPEPODS", "OTHER",
];

/** Parasites are not wounds and have no scar colour. A form that demands an
 *  unanswerable field teaches labelers the form is noise. */
const TYPES_WITHOUT_COLOR = ["COPEPODS"];

/** Which flank the mark is on. NOT `sides_visible` — see the module note. */
const SCAR_SIDES = ["Left", "Right"];

const ZONE_LABELS = {
  "1": "Head", "2": "Nape", "3": "Above Gills", "4": "Gills",
  "5": "Saddle", "6": "Flank", "7": "Aft Dorsal",
  "8": "Pelvis", "9": "Peduncle",
  D: "Dorsal Fin", P: "Pectoral Fin", T: "Tail",
};

const COLORS = ["PINK", "WHITE", "BLACK", "GREY", "OTHER"];
const COLOR_HEX = {
  PINK:  "#ff9bb0",
  WHITE: "#f0f0f0",
  BLACK: "#222",
  GREY:  "#888",
  OTHER: "#c9a26d",
};

/** What each star means, in the labeler's own words.
 *
 *  Confidence is the only field where the SAME number from two people has to
 *  mean the same thing, because the consensus engine averages it: a scar's
 *  decision threshold is "3+ agreeing raters at mean confidence >= 3", so one
 *  labeler's generous 4 and another's cautious 4 are added together as though
 *  they were one scale. A rubric is what makes them one scale.
 *
 *  `means` is the definition; `example` is the sentence a labeler would say out
 *  loud at that level, which is what people actually recognise themselves in.
 *  Both render in the info modal (#confidence-modal) and `means` is the star's
 *  hover title — all from here, so the words cannot drift between the main form
 *  and the triage card the way the colours did. */
const CONFIDENCE_RUBRIC = {
  5: {
    name: "certain",
    means: "The scar shape, depth, and pattern unambiguously match this type. I'd defend this in court.",
    example: "Multiple clear frames confirm. No alternative type is plausible.",
  },
  4: {
    name: "confident",
    means: "Type is clear but one frame or one feature is slightly ambiguous.",
    example: "One alternative is plausible but I'd reject it.",
  },
  3: {
    name: "most-likely",
    means: "Two types are plausible; this one is more consistent with what I see.",
    example: "\u201cIt's probably BITE but could be SCRATCH\u201d",
  },
  2: {
    name: "best guess",
    means: "Three or more types could fit. I'm picking the most consistent.",
    example: "\u201cIt's some kind of trauma, calling it SCRAPE for now\u201d",
  },
  1: {
    name: "guess",
    means: "I really don't know. Picking something because the type field is required.",
    example: "\u201cIf you forced me to pick, this.\u201d",
  },
};

/** The levels high-to-low — the order the rubric is read in. Descending on
 *  purpose: a labeler opens this to ask "am I allowed to say 5?", not to count
 *  up from 1. */
const CONFIDENCE_LEVELS = [5, 4, 3, 2, 1];

function needsColour(scarType) {
  return !TYPES_WITHOUT_COLOR.includes(String(scarType || "").toUpperCase());
}

/** Sides to OFFER, including whatever this record already holds.
 *
 *  Rows written before the split may carry "Both". Dropping the option must not
 *  silently rewrite an existing answer to something the labeler did not choose,
 *  so a legacy value stays selectable on the record that has it and is offered
 *  to nobody else. */
function sidesFor(currentValue) {
  const v = String(currentValue || "");
  return (v && !SCAR_SIDES.includes(v)) ? SCAR_SIDES.concat([v]) : SCAR_SIDES.slice();
}

const _VOCAB = {
  SCAR_TYPES, TYPES_WITHOUT_COLOR, SCAR_SIDES, ZONE_LABELS,
  COLORS, COLOR_HEX, CONFIDENCE_RUBRIC, CONFIDENCE_LEVELS, needsColour, sidesFor,
};

// Assigned by its literal name, not through the `root` alias: tests/test_dom_targets
// scans for `window.X =` to catch a JS file reading a global nothing assigns, and an
// aliased export is invisible to it. That is not pedantry — pose_overlay.js exported
// via `root.PoseOverlay` and went 154 lines dead without anything noticing.
if (typeof window !== "undefined") window.ScarVocab = _VOCAB;
else root.ScarVocab = _VOCAB;

})(typeof window !== "undefined" ? window : globalThis);
