#!/usr/bin/env python3
"""Lay out the Research bubbles as a drifting field.

The page used to be a heading, a lede and six labelled pods above a grid. All of
that scaffolding is gone: the nine bubbles are the page now, rising through the
same water the WebGL backdrop is drawing and wrapping round when they clear the
top. Whoever the work was done with is on the panel that opens; a circle two
hundred pixels across cannot carry it as well as it can carry the question the
project was trying to answer, which is what the labels say instead.

The drift is pure CSS. Each cell gets a lane, a phase offset and a sway of its
own; the keyframes and the pausing rules live in css/path-ocean.css. Nothing
here needs a script at runtime.

Regenerating replaces whatever sits between the two BUBBLE FIELD markers in
index.html. Edit this file, not the HTML.

Usage: python3 tools/build_bubble_field.py
"""

from pathlib import Path

V2 = Path(__file__).resolve().parent.parent
IDX = V2 / 'index.html'

OPEN_MARK = '<!-- BUBBLE FIELD: generated by tools/build_bubble_field.py -->'
CLOSE_MARK = '<!-- /BUBBLE FIELD -->'

IND = ' ' * 12

# key -> label. Each names what the project was trying to find out, not the
# animal, the dataset or the instrument. The old ~35 character ceiling was there
# because the text had to fit inside the circle; it sits above the disc now and
# wraps against a max-width, so the limit is legibility rather than geometry.
#
# The label is also the button's whole accessible name — the photograph is
# alt="" — so it has to stand on its own with no picture and no panel.
BUBBLES = [
    # The panel's own third research question, verbatim in spirit: behaviour
    # read off an AXY tag and a fin-mounted camera, not body condition.
    ('shark',       'What sharks do when no one is watching'),
    ('anchor',      'Tracking animals without drift'),
    ('relay',       'Telemetry where there is none'),
    # His own talk was titled "Accelerating Data Ingestion into FathomNet
    # Database", which is the umbrella the schema, licensing, API and corpus
    # fill all sat under. The old label named only the segmentation strand.
    ('fathomnet',   'Speeding up deep-sea data ingestion'),
    # "zombie urchin" is his own term from the v1 site, where it always carried
    # the quotes and the noun. Both are kept: "zombies" alone has no referent,
    # and this string is all a screen reader gets.
    ('aquaculture', 'Turning &ldquo;zombie&rdquo; urchins into a fishery'),
    # The work is an eleven-step analysis pipeline whose core is a curve-quality
    # classifier, so the label names the inference rather than the microbiology.
    ('jue',         'Which growth curves can be trusted'),
    ('porpoise',    'Mark-recapture without tagging'),
    ('southafrica', 'Surveying an unfamiliar coast'),
    ('fieldops',    'Getting to where the data is'),
]

# Lanes are fractions of the width a bubble can travel across: 0 sits flush with
# the left edge of the stage, 1 flush with the right, so nothing is ever half off
# screen however wide the viewport gets. They are spread out and then nudged off
# the even spacing, so the field never resolves into a row.
#
# Phases run on the golden ratio, which puts two bubbles in neighbouring lanes
# most of a screen apart vertically — the only arrangement that keeps nine of
# them from colliding while they all travel at the same speed.
LANES = [0.04, 0.17, 0.30, 0.44, 0.53, 0.66, 0.79, 0.90, 0.98]
LANE_JITTER = [0.015, -0.012, 0.021, -0.007, 0.019, -0.016, 0.010, -0.021, -0.013]
PHASE_JITTER = [0.012, -0.021, 0.017, -0.009, 0.024, -0.014, 0.006, -0.019, 0.011]

RISE_SECONDS = 46          # one lap of the field, top to bottom
GOLDEN = 0.6180339887


def cell(i, key, label):
    lane = min(1.0, max(0.0, LANES[i] + LANE_JITTER[i]))
    phase = ((i * GOLDEN) % 1.0) + PHASE_JITTER[i]
    phase %= 1.0

    # Sway periods are deliberately mutual non-multiples, so no two bubbles
    # ever fall into step for long
    sway_dur = 9.4 + (i * 1.37) % 5.6
    sway_delay = -(i * 2.9) % sway_dur
    sway = 0.8 + (i * 0.31) % 1.1
    scale = 0.92 + (i * 0.37) % 0.16

    # Stacking order. Without one, overlapping bubbles paint in DOM order, so
    # whichever happens to be later in the markup is in front of its neighbour
    # for the whole visit — hold one under the pointer until it drifts over
    # another and the overlap looks stuck rather than like depth. Ordering by
    # size instead makes a bigger bubble read as the nearer one, every time.
    z = round(scale * 100)

    style = (
        f'--lane: {lane:.3f}; '
        f'--rise-delay: -{phase * RISE_SECONDS:.1f}s; '
        f'--sway-dur: {sway_dur:.1f}s; '
        f'--sway-delay: -{sway_delay:.1f}s; '
        f'--sway: {sway:.2f}rem; '
        f'--scale: {scale:.2f}; '
        f'--z: {z}'
    )

    return [
        f'{IND}    <li class="bubble-cell" style="{style}">',
        f'{IND}        <div class="bubble-float">',
        # The label rides above the bubble rather than inside it: the button is
        # a circle with overflow hidden, so anything outside the disc is clipped.
        # It names the button through aria-labelledby so the string a screen
        # reader gets is the same one on screen, not a second copy of it.
        f'{IND}            <p class="bubble-name" id="bubble-label-{key}">{label}</p>',
        f'{IND}            <button type="button" class="research-bubble" data-panel="{key}"'
        f' aria-labelledby="bubble-label-{key}"'
        ' aria-expanded="false" aria-haspopup="dialog">',
        f'{IND}                <img class="bubble-photo" src="assets/bubbles/{key}.avif"'
        ' alt="" width="440" height="440" loading="lazy" decoding="async">',
        f'{IND}                <span class="bubble-gloss" aria-hidden="true"></span>',
        f'{IND}            </button>',
        f'{IND}        </div>',
        f'{IND}    </li>',
    ]


def render():
    out = [
        f'{IND}{OPEN_MARK}',
        f'{IND}<ul class="bubble-field" id="bubble-field" aria-label="Research projects">',
    ]
    for i, (key, label) in enumerate(BUBBLES):
        out += cell(i, key, label)
    out += [
        f'{IND}</ul>',
        f'{IND}{CLOSE_MARK}',
    ]
    return '\n'.join(out)


def main():
    s = IDX.read_text()
    start = s.index(OPEN_MARK) - len(IND)
    end = s.index(CLOSE_MARK) + len(CLOSE_MARK)
    IDX.write_text(s[:start] + render() + s[end:])
    print(f'{len(BUBBLES)} bubbles, {RISE_SECONDS}s lap')


if __name__ == '__main__':
    main()
